# Generated by Django 5.0.1 on 2024-01-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.DeleteModel(
            name='TaskDependency',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
