# Generated by Django 5.0.1 on 2024-01-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='task',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
