# Generated by Django 5.0.1 on 2024-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_project_project_file_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
