# Generated by Django 5.0.1 on 2024-04-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complete',
            new_name='is_done',
        ),
    ]
